<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Phim;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = [
            [
                'ten_phim' => 'Avengers: Endgame',
                'ten_goc' => 'Avengers: Endgame',
                'do_dai' => 181,
                'mo_ta' => 'Sau sự kiện tàn phá của Avengers: Infinity War, vũ trụ đang trong tình trạng đổ nát. Với sự giúp đỡ của các đồng minh còn lại, Avengers tập hợp lại một lần nữa để đảo ngược hành động của Thanos và khôi phục lại trật tự cho vũ trụ.',
                'dao_dien' => 'Anthony Russo, Joe Russo',
                'dien_vien' => 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson',
                'the_loai' => 'Siêu anh hùng, Hành động, Khoa học viễn tưởng',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2019-04-26',
                'ngay_ket_thuc' => '2019-08-30',
                'trailer' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 8.4,
                'so_luot_danh_gia' => 1250000,
            ],
            [
                'ten_phim' => 'Spider-Man: No Way Home',
                'ten_goc' => 'Spider-Man: No Way Home',
                'do_dai' => 148,
                'mo_ta' => 'Với danh tính của Spider-Man đã bị tiết lộ, Peter Parker yêu cầu Doctor Strange giúp đỡ. Khi một phép thuật đi sai, Peter phải khám phá ý nghĩa thực sự của việc là Spider-Man.',
                'dao_dien' => 'Jon Watts',
                'dien_vien' => 'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
                'the_loai' => 'Siêu anh hùng, Hành động, Khoa học viễn tưởng',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2021-12-17',
                'ngay_ket_thuc' => '2022-03-15',
                'trailer' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 8.2,
                'so_luot_danh_gia' => 980000,
            ],
            [
                'ten_phim' => 'Top Gun: Maverick',
                'ten_goc' => 'Top Gun: Maverick',
                'do_dai' => 131,
                'mo_ta' => 'Sau hơn ba mươi năm phục vụ như một trong những phi công hàng đầu của Hải quân, Pete "Maverick" Mitchell vẫn ở đúng nơi anh thuộc về, đẩy ranh giới như một phi công thử nghiệm dũng cảm.',
                'dao_dien' => 'Joseph Kosinski',
                'dien_vien' => 'Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm',
                'the_loai' => 'Hành động, Chính kịch',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2022-05-27',
                'ngay_ket_thuc' => '2022-09-15',
                'trailer' => 'https://www.youtube.com/watch?v=qSqVVswa420',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 8.3,
                'so_luot_danh_gia' => 750000,
            ],
            [
                'ten_phim' => 'The Batman',
                'ten_goc' => 'The Batman',
                'do_dai' => 176,
                'mo_ta' => 'Khi một kẻ giết người nhắm vào giới thượng lưu của Gotham với một loạt các âm mưu tàn bạo, Batman phải điều tra lịch sử đen tối của thành phố và tự hỏi liệu gia đình mình có liên quan gì đến tất cả.',
                'dao_dien' => 'Matt Reeves',
                'dien_vien' => 'Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright',
                'the_loai' => 'Tội phạm, Bí ẩn, Hành động',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C16',
                'ngay_khoi_chieu' => '2022-03-04',
                'ngay_ket_thuc' => '2022-06-15',
                'trailer' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 7.8,
                'so_luot_danh_gia' => 650000,
            ],
            [
                'ten_phim' => 'Black Widow',
                'ten_goc' => 'Black Widow',
                'do_dai' => 134,
                'mo_ta' => 'Natasha Romanoff, còn được gọi là Black Widow, phải đối mặt với những phần đen tối nhất trong hồ sơ của cô khi một âm mưu nguy hiểm liên quan đến quá khứ của cô nổi lên.',
                'dao_dien' => 'Cate Shortland',
                'dien_vien' => 'Scarlett Johansson, Florence Pugh, David Harbour, Rachel Weisz',
                'the_loai' => 'Siêu anh hùng, Hành động, Gián điệp',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2021-07-09',
                'ngay_ket_thuc' => '2021-10-15',
                'trailer' => 'https://www.youtube.com/watch?v=ybji16u608U',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 6.7,
                'so_luot_danh_gia' => 420000,
            ],
            [
                'ten_phim' => 'Dune',
                'ten_goc' => 'Dune',
                'do_dai' => 155,
                'mo_ta' => 'Paul Atreides, một thiếu niên tài năng và tài năng, phải đi đến hành tinh nguy hiểm nhất trong vũ trụ để đảm bảo tương lai của gia đình và người dân của anh.',
                'dao_dien' => 'Denis Villeneuve',
                'dien_vien' => 'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Josh Brolin',
                'the_loai' => 'Khoa học viễn tưởng, Phiêu lưu, Chính kịch',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2021-10-22',
                'ngay_ket_thuc' => '2022-01-15',
                'trailer' => 'https://www.youtube.com/watch?v=n9xhJrPXop4',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 8.0,
                'so_luot_danh_gia' => 580000,
            ],
            [
                'ten_phim' => 'No Time to Die',
                'ten_goc' => 'No Time to Die',
                'do_dai' => 163,
                'mo_ta' => 'James Bond đã rời khỏi hoạt động và đang tận hưởng cuộc sống yên bình ở Jamaica. Nhưng sự yên bình của anh không kéo dài lâu khi Felix Leiter, bạn cũ của CIA, xuất hiện để yêu cầu sự giúp đỡ.',
                'dao_dien' => 'Cary Joji Fukunaga',
                'dien_vien' => 'Daniel Craig, Ana de Armas, Rami Malek, Léa Seydoux',
                'the_loai' => 'Hành động, Gián điệp, Phiêu lưu',
                'quoc_gia' => 'Anh',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2021-10-08',
                'ngay_ket_thuc' => '2022-01-20',
                'trailer' => 'https://www.youtube.com/watch?v=BIhNsAtPbPI',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 7.3,
                'so_luot_danh_gia' => 380000,
            ],
            [
                'ten_phim' => 'Fast & Furious 9',
                'ten_goc' => 'F9',
                'do_dai' => 143,
                'mo_ta' => 'Dom Toretto đang sống cuộc sống yên bình với Letty và con trai nhỏ Brian, nhưng họ biết rằng nguy hiểm luôn rình rập bên cạnh. Lần này, mối đe dọa sẽ buộc Dom phải đối mặt với những sai lầm trong quá khứ.',
                'dao_dien' => 'Justin Lin',
                'dien_vien' => 'Vin Diesel, Michelle Rodriguez, Tyrese Gibson, Ludacris',
                'the_loai' => 'Hành động, Tội phạm, Phiêu lưu',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2021-06-25',
                'ngay_ket_thuc' => '2021-09-15',
                'trailer' => 'https://www.youtube.com/watch?v=aSiDu3Ywi8E',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 5.2,
                'so_luot_danh_gia' => 280000,
            ],
            [
                'ten_phim' => 'Shang-Chi and the Legend of the Ten Rings',
                'ten_goc' => 'Shang-Chi and the Legend of the Ten Rings',
                'do_dai' => 132,
                'mo_ta' => 'Shang-Chi phải đối mặt với quá khứ mà anh đã cố gắng để lại phía sau khi anh bị lôi kéo vào mạng lưới của tổ chức Ten Rings bí ẩn.',
                'dao_dien' => 'Destin Daniel Cretton',
                'dien_vien' => 'Simu Liu, Awkwafina, Tony Leung, Michelle Yeoh',
                'the_loai' => 'Siêu anh hùng, Hành động, Phiêu lưu',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2021-09-03',
                'ngay_ket_thuc' => '2021-12-15',
                'trailer' => 'https://www.youtube.com/watch?v=8YjFbMbfXaQ',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 7.4,
                'so_luot_danh_gia' => 450000,
            ],
            [
                'ten_phim' => 'Eternals',
                'ten_goc' => 'Eternals',
                'do_dai' => 157,
                'mo_ta' => 'Sau sự kiện của Avengers: Endgame, một sự kiện bất ngờ buộc các Eternals phải ra khỏi bóng tối để tái hợp chống lại kẻ thù cổ xưa nhất của loài người: Deviants.',
                'dao_dien' => 'Chloé Zhao',
                'dien_vien' => 'Gemma Chan, Richard Madden, Angelina Jolie, Salma Hayek',
                'the_loai' => 'Siêu anh hùng, Khoa học viễn tưởng, Hành động',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2021-11-05',
                'ngay_ket_thuc' => '2022-02-15',
                'trailer' => 'https://www.youtube.com/watch?v=x_me3xsvDgk',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 6.3,
                'so_luot_danh_gia' => 320000,
            ],
            // Phim đang chiếu
            [
                'ten_phim' => 'Avatar: The Way of Water',
                'ten_goc' => 'Avatar: The Way of Water',
                'do_dai' => 192,
                'mo_ta' => 'Jake Sully và gia đình của anh đang khám phá các vùng biển của Pandora, gặp gỡ các sinh vật biển mới và khám phá những bí mật của đại dương.',
                'dao_dien' => 'James Cameron',
                'dien_vien' => 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang',
                'the_loai' => 'Khoa học viễn tưởng, Phiêu lưu, Hành động',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2022-12-16',
                'ngay_ket_thuc' => '2023-03-15',
                'trailer' => 'https://www.youtube.com/watch?v=d9MyW72ELq0',
                'trang_thai' => 'dang_chieu',
                'diem_danh_gia' => 7.8,
                'so_luot_danh_gia' => 680000,
            ],
            [
                'ten_phim' => 'Black Panther: Wakanda Forever',
                'ten_goc' => 'Black Panther: Wakanda Forever',
                'do_dai' => 161,
                'mo_ta' => 'Sau cái chết của Vua T\'Challa, Wakanda phải đối mặt với những thách thức mới khi các quốc gia khác tìm cách khai thác vibranium.',
                'dao_dien' => 'Ryan Coogler',
                'dien_vien' => 'Letitia Wright, Lupita Nyong\'o, Danai Gurira, Winston Duke',
                'the_loai' => 'Siêu anh hùng, Hành động, Khoa học viễn tưởng',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2022-11-11',
                'ngay_ket_thuc' => '2023-02-15',
                'trailer' => 'https://www.youtube.com/watch?v=_Z3QKkl1WyM',
                'trang_thai' => 'dang_chieu',
                'diem_danh_gia' => 6.7,
                'so_luot_danh_gia' => 420000,
            ],
            // Phim sắp chiếu
            [
                'ten_phim' => 'Ant-Man and the Wasp: Quantumania',
                'ten_goc' => 'Ant-Man and the Wasp: Quantumania',
                'do_dai' => 125,
                'mo_ta' => 'Scott Lang và Hope van Dyne trở lại với một cuộc phiêu lưu mới trong Vương quốc Lượng tử, nơi họ gặp gỡ Kang the Conqueror.',
                'dao_dien' => 'Peyton Reed',
                'dien_vien' => 'Paul Rudd, Evangeline Lilly, Jonathan Majors, Michelle Pfeiffer',
                'the_loai' => 'Siêu anh hùng, Hành động, Khoa học viễn tưởng',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2023-02-17',
                'trailer' => 'https://www.youtube.com/watch?v=ZlNFpri-Y40',
                'trang_thai' => 'sap_chieu',
                'diem_danh_gia' => 0,
                'so_luot_danh_gia' => 0,
            ],
            [
                'ten_phim' => 'Guardians of the Galaxy Vol. 3',
                'ten_goc' => 'Guardians of the Galaxy Vol. 3',
                'do_dai' => 150,
                'mo_ta' => 'Cuộc phiêu lưu cuối cùng của Guardians of the Galaxy khi họ phải bảo vệ vũ trụ khỏi mối đe dọa mới.',
                'dao_dien' => 'James Gunn',
                'dien_vien' => 'Chris Pratt, Zoe Saldana, Dave Bautista, Bradley Cooper',
                'the_loai' => 'Siêu anh hùng, Hành động, Khoa học viễn tưởng',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'English',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2023-05-05',
                'trailer' => 'https://www.youtube.com/watch?v=u3V5KDHRQvk',
                'trang_thai' => 'sap_chieu',
                'diem_danh_gia' => 0,
                'so_luot_danh_gia' => 0,
            ],
            // Phim Việt Nam
            [
                'ten_phim' => 'Bố Già',
                'ten_goc' => 'Bố Già',
                'do_dai' => 128,
                'mo_ta' => 'Câu chuyện về một ông bố già và những đứa con trong gia đình, với những tình huống hài hước và cảm động.',
                'dao_dien' => 'Trấn Thành',
                'dien_vien' => 'Trấn Thành, Tuấn Trần, Lan Ngọc, Lê Giang',
                'the_loai' => 'Hài hước, Gia đình, Chính kịch',
                'quoc_gia' => 'Việt Nam',
                'ngon_ngu' => 'Tiếng Việt',
                'do_tuoi' => 'P',
                'ngay_khoi_chieu' => '2021-04-16',
                'ngay_ket_thuc' => '2021-07-15',
                'trailer' => 'https://www.youtube.com/watch?v=1jkw2JPCl18',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 8.5,
                'so_luot_danh_gia' => 1200000,
            ],
            [
                'ten_phim' => 'Mai',
                'ten_goc' => 'Mai',
                'do_dai' => 135,
                'mo_ta' => 'Câu chuyện về Mai, một cô gái trẻ với những ước mơ và khát vọng trong cuộc sống hiện đại.',
                'dao_dien' => 'Tran Thanh',
                'dien_vien' => 'Phương Anh Đào, Tuấn Trần, Kiều Minh Tuấn',
                'the_loai' => 'Tình cảm, Chính kịch',
                'quoc_gia' => 'Việt Nam',
                'ngon_ngu' => 'Tiếng Việt',
                'do_tuoi' => 'C13',
                'ngay_khoi_chieu' => '2022-02-10',
                'ngay_ket_thuc' => '2022-05-15',
                'trailer' => 'https://www.youtube.com/watch?v=example',
                'trang_thai' => 'ngung_chieu',
                'diem_danh_gia' => 7.2,
                'so_luot_danh_gia' => 380000,
            ],
        ];

        foreach ($movies as $movie) {
            Phim::create($movie);
        }
    }
}