<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Phim;
use Carbon\Carbon;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing movies
        Phim::truncate();
        
        $movies = [
            [
                'ten_phim' => 'Interstellar',
                'ten_goc' => 'Interstellar',
                'do_dai' => 169,
                'poster' => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                'mo_ta' => 'Cuộc phiêu lưu vũ trụ đầy kịch tính với những hiệu ứng hình ảnh tuyệt đẹp và cốt truyện hấp dẫn. Một nhóm phi hành gia dũng cảm khám phá những bí mật của vũ trụ và tìm kiếm hành tinh mới cho nhân loại.',
                'dao_dien' => 'Christopher Nolan',
                'dien_vien' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine',
                'the_loai' => 'Khoa học viễn tưởng, Phiêu lưu, Drama',
                'quoc_gia' => 'Mỹ, Anh',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
                'ngay_khoi_chieu' => Carbon::now()->subDays(5),
                'ngay_ket_thuc' => Carbon::now()->addDays(20),
                'diem_danh_gia' => 8.6,
                'so_luot_danh_gia' => 125000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'The Dark Knight',
                'ten_goc' => 'The Dark Knight',
                'do_dai' => 152,
                'poster' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'mo_ta' => 'Batman phải đối mặt với kẻ thù nguy hiểm nhất của mình - Joker. Một cuộc chiến giữa thiện và ác với những tình tiết bất ngờ và kịch tính.',
                'dao_dien' => 'Christopher Nolan',
                'dien_vien' => 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine',
                'the_loai' => 'Hành động, Tội phạm, Drama',
                'quoc_gia' => 'Mỹ, Anh',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T16',
                'trailer' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'ngay_khoi_chieu' => Carbon::now()->subDays(3),
                'ngay_ket_thuc' => Carbon::now()->addDays(25),
                'diem_danh_gia' => 9.0,
                'so_luot_danh_gia' => 2500000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'Inception',
                'ten_goc' => 'Inception',
                'do_dai' => 148,
                'poster' => 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
                'mo_ta' => 'Một chuyên gia đánh cắp giấc mơ được giao nhiệm vụ bất khả thi: cấy một ý tưởng vào tiềm thức của ai đó. Một bộ phim khoa học viễn tưởng đầy trí tuệ và kịch tính.',
                'dao_dien' => 'Christopher Nolan',
                'dien_vien' => 'Leonardo DiCaprio, Marion Cotillard, Tom Hardy, Ellen Page',
                'the_loai' => 'Khoa học viễn tưởng, Hành động, Thriller',
                'quoc_gia' => 'Mỹ, Anh',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'ngay_khoi_chieu' => Carbon::now()->subDays(10),
                'ngay_ket_thuc' => Carbon::now()->addDays(15),
                'diem_danh_gia' => 8.8,
                'so_luot_danh_gia' => 2000000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'The Matrix',
                'ten_goc' => 'The Matrix',
                'do_dai' => 136,
                'poster' => 'https://image.tmdb.org/t/p/w500/f89q3lefM2kSVVBDowNwQxIC7D9.jpg',
                'mo_ta' => 'Cuộc chiến giữa con người và máy móc trong thế giới ảo. Neo phải học cách sử dụng sức mạnh của mình để cứu nhân loại khỏi thực tế ảo.',
                'dao_dien' => 'Lana Wachowski, Lilly Wachowski',
                'dien_vien' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving',
                'the_loai' => 'Khoa học viễn tưởng, Hành động',
                'quoc_gia' => 'Mỹ, Úc',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T16',
                'trailer' => 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
                'ngay_khoi_chieu' => Carbon::now()->subDays(7),
                'ngay_ket_thuc' => Carbon::now()->addDays(18),
                'diem_danh_gia' => 8.7,
                'so_luot_danh_gia' => 1800000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'Parasite',
                'ten_goc' => '기생충',
                'do_dai' => 132,
                'poster' => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'mo_ta' => 'Một gia đình nghèo khó lừa dối một gia đình giàu có để có được việc làm. Một bộ phim đầy bất ngờ và kịch tính về sự phân tầng xã hội.',
                'dao_dien' => 'Bong Joon-ho',
                'dien_vien' => 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik',
                'the_loai' => 'Drama, Thriller, Hài',
                'quoc_gia' => 'Hàn Quốc',
                'ngon_ngu' => 'Tiếng Hàn',
                'do_tuoi' => 'T16',
                'trailer' => 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
                'ngay_khoi_chieu' => Carbon::now()->subDays(2),
                'ngay_ket_thuc' => Carbon::now()->addDays(28),
                'diem_danh_gia' => 8.5,
                'so_luot_danh_gia' => 850000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'Avengers: Endgame',
                'ten_goc' => 'Avengers: Endgame',
                'do_dai' => 181,
                'poster' => 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
                'mo_ta' => 'Trận chiến cuối cùng của các siêu anh hùng để cứu vũ trụ. Một bộ phim hành động hoành tráng với những khoảnh khắc cảm động và kịch tính.',
                'dao_dien' => 'Anthony Russo, Joe Russo',
                'dien_vien' => 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
                'the_loai' => 'Hành động, Khoa học viễn tưởng, Phiêu lưu',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'ngay_khoi_chieu' => Carbon::now()->subDays(1),
                'ngay_ket_thuc' => Carbon::now()->addDays(30),
                'diem_danh_gia' => 8.4,
                'so_luot_danh_gia' => 3200000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'Spider-Man: No Way Home',
                'ten_goc' => 'Spider-Man: No Way Home',
                'do_dai' => 148,
                'poster' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
                'mo_ta' => 'Peter Parker phải đối mặt với hậu quả khi danh tính của anh bị tiết lộ. Anh phải nhờ đến Doctor Strange để giúp đỡ, nhưng điều này dẫn đến những hậu quả không lường trước.',
                'dao_dien' => 'Jon Watts',
                'dien_vien' => 'Tom Holland, Zendaya, Benedict Cumberbatch, Willem Dafoe',
                'the_loai' => 'Hành động, Khoa học viễn tưởng, Phiêu lưu',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
                'ngay_khoi_chieu' => Carbon::now()->subDays(4),
                'ngay_ket_thuc' => Carbon::now()->addDays(22),
                'diem_danh_gia' => 8.3,
                'so_luot_danh_gia' => 1500000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'Dune',
                'ten_goc' => 'Dune',
                'do_dai' => 155,
                'poster' => 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
                'mo_ta' => 'Câu chuyện về Paul Atreides, một thanh niên tài năng phải đến hành tinh sa mạc nguy hiểm nhất trong vũ trụ để bảo vệ tương lai của gia đình và dân tộc.',
                'dao_dien' => 'Denis Villeneuve',
                'dien_vien' => 'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Zendaya',
                'the_loai' => 'Khoa học viễn tưởng, Phiêu lưu, Drama',
                'quoc_gia' => 'Mỹ, Canada',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=8g18jFHCLXk',
                'ngay_khoi_chieu' => Carbon::now()->subDays(6),
                'ngay_ket_thuc' => Carbon::now()->addDays(20),
                'diem_danh_gia' => 8.0,
                'so_luot_danh_gia' => 950000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'Top Gun: Maverick',
                'ten_goc' => 'Top Gun: Maverick',
                'do_dai' => 130,
                'poster' => 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
                'mo_ta' => 'Sau hơn 30 năm phục vụ, Maverick vẫn là một trong những phi công xuất sắc nhất của Hải quân. Anh phải đối mặt với quá khứ và đào tạo một nhóm phi công trẻ cho một nhiệm vụ nguy hiểm.',
                'dao_dien' => 'Joseph Kosinski',
                'dien_vien' => 'Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm',
                'the_loai' => 'Hành động, Drama',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=giXco2jaZ_4',
                'ngay_khoi_chieu' => Carbon::now()->subDays(8),
                'ngay_ket_thuc' => Carbon::now()->addDays(17),
                'diem_danh_gia' => 8.2,
                'so_luot_danh_gia' => 1100000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'Everything Everywhere All at Once',
                'ten_goc' => 'Everything Everywhere All at Once',
                'do_dai' => 139,
                'poster' => 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
                'mo_ta' => 'Một người phụ nữ trung niên phải cứu vũ trụ bằng cách khám phá các phiên bản khác của chính mình trong các vũ trụ song song.',
                'dao_dien' => 'Daniel Kwan, Daniel Scheinert',
                'dien_vien' => 'Michelle Yeoh, Stephanie Hsu, Ke Huy Quan, Jamie Lee Curtis',
                'the_loai' => 'Khoa học viễn tưởng, Hài, Drama',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh, Tiếng Quan Thoại',
                'do_tuoi' => 'T16',
                'trailer' => 'https://www.youtube.com/watch?v=wxN1T1uxQ2g',
                'ngay_khoi_chieu' => Carbon::now()->subDays(12),
                'ngay_ket_thuc' => Carbon::now()->addDays(13),
                'diem_danh_gia' => 8.1,
                'so_luot_danh_gia' => 750000,
                'trang_thai' => 'dang_chieu',
            ],
            [
                'ten_phim' => 'The Batman',
                'ten_goc' => 'The Batman',
                'do_dai' => 176,
                'poster' => 'https://image.tmdb.org/t/p/w500/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
                'mo_ta' => 'Batman điều tra một loạt các vụ giết người bí ẩn và phát hiện ra một mạng lưới tham nhũng ảnh hưởng đến gia đình mình.',
                'dao_dien' => 'Matt Reeves',
                'dien_vien' => 'Robert Pattinson, Zoë Kravitz, Paul Dano, Colin Farrell',
                'the_loai' => 'Hành động, Tội phạm, Drama',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T16',
                'trailer' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
                'ngay_khoi_chieu' => Carbon::now()->addDays(5),
                'ngay_ket_thuc' => Carbon::now()->addDays(35),
                'diem_danh_gia' => 7.8,
                'so_luot_danh_gia' => 680000,
                'trang_thai' => 'sap_chieu',
            ],
            [
                'ten_phim' => 'Doctor Strange in the Multiverse of Madness',
                'ten_goc' => 'Doctor Strange in the Multiverse of Madness',
                'do_dai' => 126,
                'poster' => 'https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamX371P3sTZHKj2m.jpg',
                'mo_ta' => 'Doctor Strange phải đối mặt với hậu quả khi mở ra đa vũ trụ. Anh phải hợp tác với một phiên bản khác của mình để ngăn chặn một mối đe dọa mới.',
                'dao_dien' => 'Sam Raimi',
                'dien_vien' => 'Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor, Xochitl Gomez',
                'the_loai' => 'Hành động, Khoa học viễn tưởng, Phiêu lưu',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=aWzlQ2N6qqg',
                'ngay_khoi_chieu' => Carbon::now()->addDays(7),
                'ngay_ket_thuc' => Carbon::now()->addDays(37),
                'diem_danh_gia' => 7.5,
                'so_luot_danh_gia' => 520000,
                'trang_thai' => 'sap_chieu',
            ],
            [
                'ten_phim' => 'Black Panther: Wakanda Forever',
                'ten_goc' => 'Black Panther: Wakanda Forever',
                'do_dai' => 161,
                'poster' => 'https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
                'mo_ta' => 'Các nhà lãnh đạo của Wakanda phải đoàn kết để bảo vệ quốc gia của họ khỏi sự can thiệp của các thế lực thế giới sau cái chết của Vua T\'Challa.',
                'dao_dien' => 'Ryan Coogler',
                'dien_vien' => 'Letitia Wright, Lupita Nyong\'o, Danai Gurira, Winston Duke',
                'the_loai' => 'Hành động, Khoa học viễn tưởng, Drama',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=_Z3QKkl1WyM',
                'ngay_khoi_chieu' => Carbon::now()->addDays(10),
                'ngay_ket_thuc' => Carbon::now()->addDays(40),
                'diem_danh_gia' => 7.2,
                'so_luot_danh_gia' => 420000,
                'trang_thai' => 'sap_chieu',
            ],
            [
                'ten_phim' => 'Avatar: The Way of Water',
                'ten_goc' => 'Avatar: The Way of Water',
                'do_dai' => 192,
                'poster' => 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
                'mo_ta' => 'Jake Sully và Ney\'tiri đã thành lập một gia đình và làm mọi thứ có thể để ở bên nhau. Tuy nhiên, họ phải rời khỏi nhà và khám phá các vùng biển của Pandora.',
                'dao_dien' => 'James Cameron',
                'dien_vien' => 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang',
                'the_loai' => 'Khoa học viễn tưởng, Phiêu lưu, Hành động',
                'quoc_gia' => 'Mỹ',
                'ngon_ngu' => 'Tiếng Anh',
                'do_tuoi' => 'T13',
                'trailer' => 'https://www.youtube.com/watch?v=d9MyW72ELq0',
                'ngay_khoi_chieu' => Carbon::now()->addDays(14),
                'ngay_ket_thuc' => Carbon::now()->addDays(44),
                'diem_danh_gia' => 7.6,
                'so_luot_danh_gia' => 580000,
                'trang_thai' => 'sap_chieu',
            ],
        ];

        foreach ($movies as $movie) {
            Phim::create($movie);
        }
    }
}
